### ISSUE TITLE
Multiple SuperTable field values inside Matrix will result in 1 item

### ISSUE THREAD

**Issue by ruudvdboom** [engram-design/FeedMe#1419] opened 2024-03-20 13:16 UTC
### Description
When importing multiple values for a Supertable field inside a matrix field. The result will end up with 1 item instead of multiple.

### Example import json
```json
[
    {
        "title": "Test",
        "slug": "test",
        "layers": [
            {
                "employees_items": [
                    {
                        "employee_titel": "Item 1",
                        "employee_id": 100
                    },
                    {
                        "employee_titel": "Item 2",
                        "employee_id": 200
                    }
                ]
            }
        ]
    }
]
```

### Steps to reproduce

1. Create field "Layers" (matrix field)
2. Inside "Layers" create a supertable field employeeItems. With the fields employeeTitle and employeeId. 
3. Create the field mapping
4. Multiple items are expected, but only the last one is imported (also viewable with the debug link)

## Possible solution?

On line 72 of SuperTable.php:
```php
$blockIndex = Hash::get($nodePathSegments, 1);
```

The $blockIndex will get the ID from the matrix layer not the supertable field. So the same key is created for every item. Hence, only the last item is imported.

Change the second param, so the correct keys are created.
```php
$blockIndex = Hash::get($nodePathSegments, 3);
```

This seems to work, but I'm not sure if this creates other problems.

### Additional info

- Craft version: 4.8.3
- PHP version: 8.2
- Plugins & versions: Feed Me 5.4.0

**Comment by ruudvdboom** [comment] 2024-03-20 13:49
My previous possible "solution" is not correct. This will also overrule previously created items on the parent level (matrix). So 2 matrix items will result in 1.

**Comment by olivierbon** [comment] 2024-03-20 15:18
Dupe of #470

**Closed as completed by olivierbon** 2024-03-20 15:18 UTC
Labels: bug
