### ISSUE TITLE
Question mapping assets

### ISSUE THREAD

**Issue by dustinwalker** [engram-design/FeedMe#6] opened 2015-05-02 17:33 UTC
I am sure it's something I am doing wrong, but I've included just the file name in the feed (Lot7 as an example in this case) and if I search that name from the asset source in Craft's admin I confirmed it returns the correct result but I can't seem get it to map on import from either a XML or JSON source. 

I've tried on two different fields with different sources, one which is all pdfs, the other all jpgs.

Any thoughts on what I am doing wrong? Other fields that need mapping (users, categories) seem to be working perfectly. 

Thanks for your help and this add-on.

**Comment by engram-design** [comment] 2015-05-02 23:59
@dustinwalker Interested - I've been testing with Assets in all of my test cases and works fine.

Are there any restrictions on your Assets field you're importing into? Like the file type, or Sources?

Send through a screenshot of your Asset field settings, as that may help.

**Comment by dustinwalker** [comment] 2015-05-03 03:07
It does, though I think I switched to not having it restrict to a single source with the same results. The source is a local source, not S3.

Screen capture of the source: https://docs.google.com/file/d/0B07oh86n7RPcRjBnc0Z3UkREOUk/
Screen capture of the list from the assets tab: https://docs.google.com/file/d/0B07oh86n7RPcYzNndUM5R1FIenM/edit

And the JSON feed (I am just trying to get prices_realized to work, also tried the preview_gallery matrix row) https://gist.github.com/dustinwalker/5da21c00b4b6bed3670b

Let me know if any additional if is helpful. I'll test some more settings tomorrow morning to see if anything works. Thanks for the help and the plugin!

**Comment by engram-design** [comment] 2015-05-03 07:40
@dustinwalker Thanks for that information. Using the exact json you're using, and adding a PDF with the same name as an entry (`Auction-12-Prices-B`) it seems to map properly. I've even messed around with the sources and all working fine.

I've made a few other optimisations and tweaks which will be commiting very soon. Might be worth you trying that out to hopefully see if that fixes things!

Out of interest, what is the primary element you're using?

**Comment by dustinwalker** [comment] 2015-05-03 12:55
Thanks for the help and looking into this. I was using "items", "item" was throwing an undefined offset error. I'll continue to try different things to see if I can get it to work.

**Comment by engram-design** [comment] 2015-05-03 12:59
The latest fix wont show that undefined offset error, but I was using 'items' in my test.

FYI - you don't even need a primary element, but this depends on if you're making the feed yourself.

It could be:

```
[
    {
        "Title": "The Title",
    },
    {
        "Title": "Another Title",
    }
]
```

Anyway - I will continue to investigate to see what is going on...

**Comment by dustinwalker** [comment] 2015-05-03 13:02
I know you mentioned it worked in your testing, but removing the limit on the sources and checking "all" does seem to fix it at least for the PDFs. Going to test the other sources again. Thanks for that hint earlier.
http://note.io/1E6zQMs

**Comment by engram-design** [comment] 2015-05-03 13:15
Interesting. I think I might bundle up screenshots of each area and send them through, just to triple make sure!

**Comment by engram-design** [comment] 2015-05-03 13:34
@dustinwalker Can you have a look at the screenshots through the provided link? That pretty much sums up how my setup it configured...

https://www.dropbox.com/sh/k2s5kvrmuyjdno2/AADKsd1ILFtCD98BaNaN2h2pa?dl=0

**Comment by dustinwalker** [comment] 2015-05-04 15:14
I double checked today and that mirrors, as far as I can tell, my setup. If I check the "all sources" it seems that fixes every import but that setting obviously doesn't affect your test.

I'll see if I can get this to a public accessible staging site today and still have the same issue. If I do, I would be happy to provide a log in. For this project after the initial import it wont really matter since I am just exploring transferring the entire install over to Craft instead and I can limit the source after the fact, but if I can track down the specific thing causing this it may be helpful for future cases.  

Thanks again for all your patience and assistance.

**Comment by engram-design** [comment] 2015-05-04 15:16
Sure, would be happy to help. I'll do the same by uploading it to our staging server - just in case its an issue with my local development machine. Sorry we couldn't resolve this easily!

**Comment by engram-design** [comment] 2016-03-21 23:44
Closing for the moment, as I'm unable to reproduce this issue. Let me know if you're still experiencing this issue and will reopen.

**Closed by engram-design** 2016-03-21 23:44 UTC

**Comment by RobErskine** [comment] 2016-06-08 18:11
Hey Josh and Justin!

Sorry to re-open an old issue, but i think I am having a similar issue. I am trying to map an external json file to a channel within Craft. All of the fields map properly, except for my "headshot" assets fieldtype, which is an Amazon s3 container (uploads, witch the "restrict uploads to a single folder" with the path being "headshots") with only an image filetype restriction.

I'm met with a lot of these errors in craft/storage/runtime/logs/feedme.log
```
[error] [plugin] [Forced] Employees: {"headshot":["Headshot cannot be blank."]}
``` 
The JSON file basically looks like this :
```
{
  employeeId: "32082",
  status: "active",
  name: "Rob Erskine",
  title: "Creative Technologist",
  department: "Innovation and Technology",
  office: "Boston, MA",
  selfie: "https://corpservices.hhcc.com/selfie/ci_admin_assets/uploads/roberskine-May232016043421pm-filter.png"
},
...
```
Would there be any issue of having feedme write to the rackspace container?

**Comment by engram-design** [comment] 2016-06-10 15:28
@RobErskine Cool, I'll see if I can reproduce on my end! Have to say haven't full tested with remote asset sources yet...
