### ISSUE TITLE
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'fieldMapping' at row 1

### ISSUE THREAD

**Issue by DynamiteGoesBoom** [engram-design/FeedMe#1446] opened 2024-05-17 20:21 UTC
### Description

For whatever reason any time I try to import a CSV into any channel/structure that has 2 Matrix Builders (we have a hero builder and a content builder) we get this error

![Screenshot 2024-05-17 at 1 47 48 PM](https://github.com/craftcms/feed-me/assets/39201467/163531f4-7a34-44e6-8bd9-8a85abe17b5b)

The weird thing is that we're not trying to import anything besides a Title and a PostDate data set.

What causes this error? Is it a database issue with the column size or something? I haven't seen this particular issue before.

### Steps to reproduce

I can grant you access to our repo or email you whatever you need

### Additional info

- Craft version: 4.9.2
- PHP version: 8.2
- Database driver & version: mariadb
- Plugins & versions: 5.4

**Comment by DynamiteGoesBoom** [comment] 2024-05-21 14:39
Is there anything that can be done with this? It's sounding more like a DB problem but hopeful that a solution can be made here.

Would upgrading to 5 help alleviate this issue?

**Comment by i-just** [comment] 2024-05-24 07:12
Hi, thanks for getting in touch! The problem is that the field mapping information is too long for the database column it’s supposed to fit into. The field mapping for a feed is stored as a JSON-like string in a `TEXT` type column, which has a limit of 65,535 characters in Maria/MySQL (PostgreSQL doesn’t have that limit).

> The weird thing is that we’re not trying to import anything besides a Title and a PostDate data set.

Field mapping stores information on all the attributes and fields for the element you’re importing to, including information on which fields and attributes not to import.

> Would upgrading to 5 help alleviate this issue?

No, unfortunately not. The column type for the feed’s field mapping is the same in Feed Me v5 (for Craft 4) and Feed Me v6 (for Craft 5).

I raised a PR to migrate to a larger column size (for Maria and MySQL), which should help with the error you’re encountering.

**Comment by angrybrad** [comment] 2024-05-27 00:20
Resolved in https://github.com/craftcms/feed-me/pull/1453 and will be included in the next release.

**Closed as completed by angrybrad** 2024-05-27 00:20 UTC
Labels: bug
