### ISSUE TITLE
Re-import changes some relations in strange and mysterious ways

### ISSUE THREAD

**Issue by ldstevens** [engram-design/FeedMe#199] opened 2017-04-13 05:28 UTC
So picking up from #196, I've been able to reproduce the bug (in one way at least), and it's weird. Here's what happens:

- I'm importing entries which have an entryImage asset field, and an entryGallery asset field. For entryImage Feed Me is set to download the file from an external URL, replacing the existing asset (though I _think_ this happens with Keep Original too). entryImage is the one which has been strange.
- Run import once, entry is loaded, but entryImage uses the first image from entryGallery (ID: 77502), which is incorrect. The correct asset is in the DB (15865), but not used...
- Run the same import again, and the associated entryImage asset ID changes, in this case to 15861 (from 77502).
- Run the same import again, and the entryImage remains the same.

If I delete the entry and re-import, I get the same sequence of events, with the same asset IDs, so that seems predictable.

Really strange! 👽 

I'll see what happens running the same import locally...

**Comment by engram-design** [comment] 2017-04-13 05:36
Any chance you can share you feed so I can replicate? It might have something to do with matching filenames, so would be great to see what you're seeing. If you can't share publicly, do get it touch via Slack!

**Comment by engram-design** [comment] 2017-04-13 07:43
Should be fixed in the [latest version](https://sgroup.com.au/plugins/feedme/download) - sorry about that! This was an issue when you had more than one assets field uploading assets. Silly mistake on my behalf there!

**Comment by ldstevens** [comment] 2017-04-13 23:58
Thanks for taking a look pre-meetup! I gave it a run last night but unfortunately got a different set of incorrect entry images, but it sounds like you're close so let's pick it up again after the weekend. Cheers Josh!

**Comment by ldstevens** [comment] 2017-04-15 23:16
Got you Slack DM thanks, just thought I'd drop a quick note here. I've run two more imports, and it seems like the multi-image upload & incorrect entry images are probably separate issues. In both imports (and previous imports) I've noticed incorrect images for single-image entries, but the kicker is they're not always the same entries. Sometimes one is consistently wrong, sometimes it's others. Really bizarre. I'll try and come up with more cut-and-dry test data to further test the issue if I get a chance in the next couple of days. Pretty hairy one to debug!

**Comment by engram-design** [comment] 2017-04-16 00:36
One possibility is that you have multiple assets with similar filenames, and they're being matched? I'd probably need to check out your setup specifically to see what might be going on. Happy to continue via Slack whenever is a good time.

**Comment by ldstevens** [comment] 2017-04-17 05:38
Yeah I don't know, most recent import I got an entry with "Daniel.CastroGarcia.JPG" instead of e.g. "super8kodak.jpg", so it seems pretty random. For this import I moved all images onto the same server to rule out network or source server issues (also made things a lot faster!). The bad entry image I spotted was the 319th entry imported, so you really have to look for them. It can seem fine at first glance for the initial imports, but then later on you spot bad ones. I'm thinking for the next test I'll generate 999 copies of the same image, with 999 dummy JSON entries, and that way it will be easier to spot mismatch entry images (i.e. "Entry 275" might have "Image 451" instead of "Image 275"). Will let you know how it goes. Will be back and deck properly tomorrow.

**Comment by ldstevens** [comment] 2017-04-17 05:40
(Might make a twig template that highlights the mismatches from that data set directly to save me trying to eyeball them too.)

**Comment by ldstevens** [comment] 2017-04-21 07:37
Just updating this to say the add-asset-from-filename functionality works now, but it's *still* providing misses. Damn. Will try rebuilding from a clean Craft install next week & running them import again to rule out any weirdness in the DB I've been using.

**Comment by ldstevens** [comment] 2017-04-21 09:10
**IT WAS THE DB!** 😓😓😓

Fresh Craft install, recreated the news section, re-imported the feed, all images matched. 

No idea how it the DB became subtly corrupt (I had been using The Architect to import settings), but I'll have fun rebuilding the whole thing from scratch next week 😰 

Sorry for all the hassle! 😓😓😓

**Comment by engram-design** [comment] 2017-04-21 10:20
Aha! Sounds like there's finally some headway on this issue. Certainly can't be sure as to what specifically might be the issue, but hopefully it'll get you heading in the right direction.

Going to close this thread for now, but re-open if the issue comes back at all!

**Comment by ldstevens** [comment] 2017-04-26 09:11
**The plot thickens...**

Just popping in here with an update to say that while I'm still experiencing the issue, it wasn't The Architect _or_ the db per se that was causing it. And it doesn't appear to be FM specifically causing it either!

My previous FM import with a minimal setup that worked must have been a fluke -- I haven't been able to reproduce a working import yet.

I rebuilt the entire setup manually (without The Architect) to ensure DB integrity, ran FM, and got mismatched images. That ruled out The Architect.

So is it a FM issue? Not so fast...

I then spent hours doing minimal test imports with FM to see if there was a setup where I could reproduce the clean import; no luck, either locally or on a dev server.

So I then fell back to plan C, which was to use Sprout Import for the images. Lo and behold, that exhibits the same behavior as FM: mismatched images.

Running Sprout Import seems to be a bit more deterministic -- I get the same 10 mismatched images with the same batch of ~300 test entries I'm working with fairly consistently, but that's not much help. But it does seem to indicate it's not a FM-specific issue. 

So the mismatched images issue is still there, but it seems it's at a lower level in Craft itself, or even Yii, who knows. Might run it by the Craft devs to get their thoughts. So strange. 

Looks like I'm going to be doing a lot of image updating by hand!

**Comment by engram-design** [comment] 2017-04-26 11:13
I'm actually looking into a similar issue with another client on this one - this time matching against existing assets, but still experiencing the mismatched images. What's worrying however, is I'm unable to replicate locally with the exact same database.

I did have to repair the DB tables for this particular client (no faults detected), but that may very well be a different issue.

**Comment by ldstevens** [comment] 2017-04-26 12:15
Ah that's interesting someone else is experiencing it, and you can't reproduce locally. What version of php & mysql are you running on your machine?

**Comment by ldstevens** [comment] 2017-04-26 12:26
(I'm running php 5.6.30 & mysql 5.7.18 for what it's worth - might try php 7 at some point.)

**Comment by ldstevens** [comment] 2017-04-26 12:26
And you're running the latest Craft 2.x I take it too? 

Anyway I'll see if I turn up anything tomorrow!

**Comment by engram-design** [comment] 2017-04-26 12:30
Running Mamp, PHP 7 (tried on 5.6), MySQL 5.6.35, latest Craft (latest Feed Me), no other plugins installed.

**Comment by ldstevens** [comment] 2017-04-27 07:09
Ah weird. For kicks I tried PHP 7 (was 5.6) and Mysql 5.6 (was 5.5) and MariaDB 10 on the dev server, just re-running Feed Me on the existing site each time, but with no luck. Not sure if running it from a clean install would make a difference,

**Comment by ldstevens** [comment] 2017-04-27 07:17
> I did have to repair the DB tables for this particular client (no faults detected), but that may very well be a different issue.

They're running MySQL with InnoDB right?

**Comment by engram-design** [comment] 2017-04-27 14:30
Yeah I believe so, although I'm no MySQL expert - the table seem to say InnoDB engine...

**Comment by ldstevens** [comment] 2017-04-28 02:40
Yeah fair enough 👍 

Couple more tests...
- Tried XML instead of JSON, still failed
- Tried breaking up 300 entries into 6 x 50 entry files, with a feed each. Running these sequentially (i.e. queued) resulted in same old mismatched images. 
- However, running them individually **corrected** the mismatched entries. (At least in that run.) Too bad I have 30k+ entries and not 300! haha.

Downloaded MAMP, will try next.

**Comment by ldstevens** [comment] 2017-04-28 03:53
No dice with MAMP :( Completely clean install too. I assume you're running something like Apache / PHP 7 / MySQL 5.6.35?

**Comment by ldstevens** [comment] 2017-04-28 04:45
Tried a minimal import with just slugs and filenames for asset matches, no dice.

**Comment by ldstevens** [comment] 2017-04-28 05:08
Ran a miss/match check against categories to see if other relations were affected; but categories seem unaffected.

**Comment by ldstevens** [comment] 2017-04-28 05:24
**I HAVE A WORKAROUND** 🎉 

Using the logic from my miss/match template, I'm generating a JSON file of misses which just contains slugs & asset filenames (no uploading). Running that seems to clear up the misses.

✨ AT LONG LAST ✨ 

Still no idea what's causing it though ¯\_(ツ)_/¯

**Comment by ldstevens** [comment] 2017-04-29 01:42
> Diving into the cause for this issue, I believe I've found the cause.

Legend! :)

**Comment by engram-design** [comment] 2017-04-29 01:48
Still trying to figure out if its Feed Me or Craft at this point, but should have something solid soon.

**Comment by ldstevens** [comment] 2017-04-29 01:53
Awesome. No stress here, just a relief to know it's not a DB data integrity issue :)

**Comment by engram-design** [comment] 2017-04-29 07:21
@ldstevens Unable to find a way to fix this through Feed Me - but not without lack of trying. I'm interested to hear if they P&T respond.

In the meantime, if you make that change to `$hash = $this->element ? spl_object_hash($this->element) : null;` I'm interested if this fixes your issue, as it has for another client.

**Comment by ldstevens** [comment] 2017-04-29 11:31
Bugger, hope P&T come back with something! Sounds like it needs to be solved Craft-side, given Sprout Import was demonstrating the same behaviour.

Will give that change a go on Monday and let you know.

**Comment by engram-design** [comment] 2017-04-29 12:11
I have got a solution thats Feed Me only, but its terribly unperformant. It'll likely slow processing down to a crawl, and max out memory.

The problem is - once the element model (the entry you're importing) is garbage collected, `spl_object_hash` will re-use the hash for an already created element model - in turn grabbing another element's content. The only way to solve this is to keep each processed element in-memory (adding to an array), but as this is keeping them in memory, my testing shows is slows processing considerably. Some feeds didn't even finish due to running out of memory.

**Comment by ldstevens** [comment] 2017-05-01 01:58
> In the meantime, if you make that change to $hash = $this->element ? spl_object_hash($this->element) : null; I'm interested if this fixes your issue, as it has for another client.

It did! Patching Craft is fine for me Thanks so much for the fix!

**Closed** 2017-05-02 12:56 UTC

**Comment by engram-design** [comment] 2017-05-02 22:00
FYI, this has been integrated into the latest [Craft 2.6.2977](https://craftcms.com/changelog#2-6-2977)
